### PR TITLE
OTP 19.x for Travis CI

### PR DESCRIPTION
**Pull request by puzza007**
Remove OTP R16*

### CODE REVIEW

**Comment by AeroNotix** [comment]
Did you remove support or just remove the testing?

**Comment by puzza007** [comment]
Just tests. What version are you on? I'll add it back.

**Comment by AeroNotix** [comment]
Well we're on R16B03 but it's no biggie. We have the version tagged for what we use any way. Just wanted to know if you would eventually stop supporting it altogether.

**Comment by puzza007** [comment]
Lemme scoop this up https://github.com/puzza007/erlang-bcrypt/pull/14

**Comment by AeroNotix** [comment]
Cheers! :+1:

**Pull request merged**
